### ISSUE TITLE
Add option to disable mappings

### ISSUE THREAD

**Issue by yutakatay** [mechatroner/rainbow_csv#11]
I don't want to change the mapping by default. So please add an option to disable the mapping.

eg. g:disable_default_mapping = 1

**Comment by mechatroner** [comment]
Done. Rainbow CSV now supports `g:disable_rainbow_key_mappings` [setting](https://github.com/mechatroner/rainbow_csv#gdisable_rainbow_key_mappings)

**Comment by yutakatay** [comment]
It worked! Thank you :smile:
