### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by angoodkind** [mechatroner/rainbow_csv#13]
Are there any keyboard shortcuts for the commands in the package?

**Comment by mechatroner** [comment]
Yep, they are actually documented in the README.md file ( https://github.com/mechatroner/rainbow_csv#key-mappings ) and in the plugin vim docs which I just fixed.

**Comment by angoodkind** [comment]
I didn't realize this is a im plugin. It works in sublimetext as well. Are there key bindings for sublimetext?

**Comment by mechatroner** [comment]
These are different plugins, but they share the same name and idea. Sublime plugin resides in a this repo: https://www.sublimetext.com/docs/3/key_bindings.html . And it has only one default key binding - F5, to start RBQL : https://github.com/mechatroner/sublime_rainbow_csv#key-mappings . But you should be able to add your own command binding: https://www.sublimetext.com/docs/3/key_bindings.html

**Comment by angoodkind** [comment]
Very cool! Thank you!
