### ISSUE TITLE
[feature] Allow user to change the path of temp file

### ISSUE THREAD

**Issue by Freed-Wu** [mechatroner/rainbow_csv#16]
Such as user can assign a variable to change `~/.rbql_table_index`,
`~/.rainbow_csv_storage` to `~/.cache/nvim/.rbql_table_index`,
`~/.cache/nvim/.rainbow_csv_storage`? or more compatible with XDG standard,
`$XDG_CACHE_HOME/nvim/.rbql_table_index`,
`$XDG_CACHE_HOME/nvim/.rainbow_csv_storage`?

Thanks!

**Comment by Freed-Wu** [comment]
```{.vim}
let s:rb_storage_dir = $HOME . '/.rainbow_csv_storage'
let s:table_names_settings = $HOME . '/.rbql_table_names'
let s:rainbow_table_index = $HOME . '/.rbql_table_index'
```

Can these codes are changed?

**Comment by dther** [comment]
I made a patch for this! See my recent pull request, above.

**Comment by mechatroner** [comment]
I merged the patch. Thank you very much, @dther!
