### ISSUE TITLE
Wijmo License Expired

### ISSUE THREAD

**Issue by boeningc** [mechatroner/rainbow_csv#21]
I see this when doing a CSV Preview.

Wijmo License

The Wijmo license in this application has expired. The license expiration date is 2/1/2021.

Please create a license or contact GrapeCity: us.sales@grapecity.com.

CLOSE
Wijmo Evaluation Version (5.20201.664)

**Comment by mechatroner** [comment]
Hi @boeningc!
It's actually a problem with another VSCode extension: "Excel Viewer", which you probably also have installed. You should submit this issue to the Excel Viewer project.

**Comment by boeningc** [comment]
Ah .. ok.  I can do that.  Thanks.
