### ISSUE TITLE
duplicate colors?

### ISSUE THREAD

**Issue by jyesselm** [mechatroner/rainbow_csv#26]
I may just really not understand but no matter what I do col 6 and 7 have the same color is there a way to fix this? See image.
![image](https://user-images.githubusercontent.com/3579125/116010994-1e0b8800-a5e8-11eb-8b55-df4ee4c25c43.png)

**Comment by mechatroner** [comment]
Hi @jyesselm! Have you tried setting the `g:rcsv_colorpairs` variable?

**Comment by jyesselm** [comment]
Ah yes I didn't understand this variable. Thanks that fixes it!
