### ISSUE TITLE
CSV tables that contain cells with newlines are not rendered properly

### ISSUE THREAD

**Issue by augusto-herrmann** [mechatroner/rainbow_csv#35]
CSV files sometimes contain cells with newlines. This is valid when the cell is properly delimited with double quotes, for instance. Many tools like LibreOffice, the [Frictionless Framework](https://github.com/frictionlessdata/framework) and even Github CSV visualization do work well with such files.

However, Rainbow CSV treats such files as invalid, and does not recognize the cell (e.g. for coloring, or the hovering tooltip with the column name).

Here is [an example](https://github.com/okfn/publicbodies/blob/main/data/br.csv) of one such file that contains newlines inside cells.

**Comment by augusto-herrmann** [comment]
Sorry if this is a duplicate issue. I have now found #3.

**Comment by augusto-herrmann** [comment]
Actually, for anyone else stumbling into this issue, the whole story [is in this issue here](https://github.com/mechatroner/vscode_rainbow_csv/issues/4#issuecomment-1192164574). To sum it up: it hasn't been implemented yet because it was believed that the available grammar was not up to the task of handling line breaks in CSV cells. However, after many years a possible solution was recently found and is being experimented upon. So there might be a solution in the future.

**Comment by mechatroner** [comment]
Hi @augusto-herrmann, I actually just released version 3.0.0 of the rainbow-csv extension in VSCode which supports cells with newlines with some limitations, see my last comment in the issue you linked. 
And BTW you opened this issue in Vim Rainbow CSV extension repository which had support for multiline fields for quite some time.

**Comment by augusto-herrmann** [comment]
That's great to know! Thanks for the heads up @mechatroner and sorry about my mistake.
