### ISSUE TITLE
rainbow color

### ISSUE THREAD

**Issue by suburbandox** [mechatroner/rainbow_csv#43]
my rainbow is not colorful enough.
is there a way to customize your rainbow? 

![image](https://github.com/mechatroner/rainbow_csv/assets/16246628/c3e26d78-4d94-4cfb-98ba-07cc8610ea1e)

**Comment by mechatroner** [comment]
Hi, it seems that you are using VSCode version of the Rainbow CSV plugin and this is the repo for Vim version of the plugin. In VSCode you can customize colors using this instruction https://github.com/mechatroner/vscode_rainbow_csv/blob/HEAD/test/color_customization_example.md#colors-customization .  And in case you are actually using the Vim version you can use this variable: https://github.com/mechatroner/rainbow_csv#grcsv_colorpairs
Hope it helps!
