### ISSUE TITLE
Searching with Nn: Status line is overwritten with column name, can't see search results

### ISSUE THREAD

**Issue by benjamin051000** [mechatroner/rainbow_csv#44]
When searching with /, usually you get an indicator of how many results appeared in the status line: 
```
[1/5]
```
This plugin writes the column name the cursor is on in the status line. I think that it is overwriting the line, though, as I can't see the results info anymore :( any ideas how to fix?

**Comment by mechatroner** [comment]
It is possible to disable showing column name in the status line:
`let g:disable_rainbow_hover = 1`
