### ISSUE TITLE
Unconditional setting of nocompatible too intrusive

### ISSUE THREAD

**Issue by Hans-Guenter** [mechatroner/rainbow_csv#7]
I observed that due to the setting of nocompatible in the function rainbow_csv#buffer_enable_rainbow_features
my viminfo setting was reset to its default values.

Therefore I think the setting must not be unconditional but only if not yet set.
Thus my suggestion for a patch of the autoload file as follows:
[diff_rainbow_csv_vim.txt](https://github.com/mechatroner/rainbow_csv/files/3529021/diff_rainbow_csv_vim.txt)

**Comment by mechatroner** [comment]
Cool, thanks! 
I though "nocompatible" is idempotent and doesn't change anything if already set.
Another approach is to show an error if user doesn't have "nocompatible" set, with suggestion to manually set it, but for now I will just use your patch.
