### ISSUE TITLE
WHERE in Python list not working for more than 10 list items

### ISSUE THREAD

**Issue by Hans-Guenter** [mechatroner/rainbow_csv#8]
I tried to define a WHERE statement for the python worker with more than 10 items in the IN list and it failed:

If one looks at the resulting worker python file one sees the following problem:

a select statement like

> Select a1 where a1 in ["1","2","3","4","5","6","7","8","9","10","11","12"]

is being translated into the following statement of the process_update function in the resulting worker file:

>if len(rhs_records) == 1 and (a1 in ["1","2","3","4","5","6","7","8","9","10","2"0,"2"1]):

I think it is quite obvious what goes wrong with the list items "11" and "12" and so on.

**Comment by mechatroner** [comment]
That's a silly bug indeed. Thanks again, @Hans-Guenter ! I will fix it.

**Comment by mechatroner** [comment]
Fixed
